### PR TITLE
Reduced FileNotFoundError stacktraces

### PR DESCRIPTION
**Pull request by jecarr**

### CODE REVIEW

**Comment by msariego-endgame** [comment]
Just out of curiosity, why do we want more detailed logs for file errors in Production?

**Comment by jecarr** [comment]
> Just out of curiosity, why do we want more detailed logs for file errors in Production?

@msariego-endgame I'm opting for less-detailed logs for file errors (unless you're asking why for that?).

I made a call to reduce these ones specifically because in one line we can still say that a search engine was not loaded. Currently, we know where the engines are being loaded from, if given just the filename we can see a particular one is missing, the stacktrace gives us quite a block to tell us an engine failed to load. This PR just reduces those errors whilst keeping non-file related errors at their usual output.

So instead of 

```
ERROR:searx.engines:Cannot load engine "acgsou"
Traceback (most recent call last):
  File ".../searx/searx/engines/__init__.py", line 77, in load_engine
    engine = load_module(engine_module + '.py', engine_dir)
  File ".../searx/searx/utils.py", line 447, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '.../searx/searx/engines/acgsou.py'
```

This PR reduces this in the logs to

```
ERROR:searx.engines:Cannot load engine "acgsou"; [Errno 2] No such file or directory: '.../searx/searx/engines/acgsou.py'
```

Because the `FileNotFoundError` in that location will be specific to engines being loaded where we know this is in `searx/searx/engines/`

**Review by KadeMorton — APPROVED** [review]
Discussed and approved.

**Comment by KadeMorton** [comment]
Discussed and merged.

**Pull request merged**
